name: Build python package for tags

on:
  push:
    tags:
      - '*'

jobs:

  tests:

    runs-on: ubuntu-latest
    env:
      FLASK_APP: "newssite:create_app()"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        make dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        make lint
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        # flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Test with pytest
      run: |
        make coverage


  build-pkg:
    needs: tests
    runs-on: ubuntu-latest
    env:
      FLASK_APP: "newssite:create_app()"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        make dist
    - uses: actions/upload-artifact@v2
      with:
        name: distribution-python
        path: dist/
        retention-days: 1
